CurhatMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('thepost/', include('thepost.urls')),
    path('thereply/', include('thereply.urls')),
    path('testimoni/', include('testimoni.urls')),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.login_request, name='login'),
    path('api/', views.UserListView.as_view(), name=None),
    path('logout/', views.logout_request, name='logout'),
]

thepost/urls.py
from django.urls import path
from .views import *

app_name = 'thepost'

urlpatterns = [
    path('', timeline, name='timeline'),
    path('search/', search, name='search'),
    path('api/', storyCurhatListView.as_view(), name=None)
]

authentication/models.py
from django.db import models

authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

from django.contrib.auth.models import User
from . import serializers
from rest_framework import generics, status
from rest_framework.response import Response

# Create your views here.

def homepage(request):
    return render(request, "homepage.html")

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("authentication:homepage")
        else:
            messages.error(request, "Invalid username or password")

    form = UserCreationForm
    return render(request, "register.html",{"form":form})

def logout_request(request):
    logout(request)
    return redirect("authentication:homepage")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        response_data = {}
        if form.is_valid():
            print("valid")
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                response_data['username']=username
                response_data['message']='You are logged in as '
                return JsonResponse(response_data)
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")

    form = AuthenticationForm()
    return render(request, "login.html", {"form":form})

class UserListView(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer

class UserCreateView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer

    def create(self, request, *args, **kwargs):
        super(UserCreateView, self).create(request, args, kwargs)
        response = {"status_code": status.HTTP_200_OK,
                    "message": "Successfully logged in",
                    "result": request.data}
        return Response(response)

class UserDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer

    def retrieve(self, request, *args, **kwargs):
        super(UserDetailView, self).retrieve(request, args, kwargs)
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        data = serializer.data
        response = {"status_code": status.HTTP_200_OK,
                    "message": "Successfully retrieved",
                    "result": data}
        return Response(response)

    def patch(self, request, *args, **kwargs):
        super(UserDetailView, self).patch(request, args, kwargs)
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        data = serializer.data
        response = {"status_code": status.HTTP_200_OK,
                    "message": "Successfully updated",
                    "result": data}
        return Response(response)

    def delete(self, request, *args, **kwargs):
        super(UserDetailView, self).delete(request, args, kwargs)
        response = {"status_code": status.HTTP_200_OK,
                    "message": "Successfully deleted"}
        return Response(response)

authentication/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>CurhatMe</title>
    <!-- <link rel="shortcut icon" type="image" href="bunga-min.png"/> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/styling.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
</head>

<body class="home">
    <div class="row align-items-center">
        <div class="col-md-5">
            <img id="logo" src="{% static 'images/logo.png' %}">
        </div> 
        <div class="col-md-7">
            <p id="tagline">Teman curhat <br>yang selalu ada</p>
            <a href="{% url 'authentication:login' %}"><button type="button" class="btn btn-secondary btn-sm" id="yuk3">yuk curhat</button></a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <script src="{% static 'js/japa.js' %}"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
     
</body>

authentication/templates/login.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<title>Login</title>

		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type = "text/css" href="{% static 'css/styling.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">

	</head>

	<body>
    <div class = "container text-center mt-5 mb-5" id="contain_bg">

    {% if user.is_authenticated %}

    <p>
    You are already logged in as {{request.user.username}}!<br>
    Click here to <a href="#modal1" class="modal-trigger red-font"> log out</a><br>
    Click here to go to your <a href="/thepost/" class="red-font"> timeline</a>
    </p>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Are you sure you want to logout?</h4>
      <p>We will miss you!</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="modal-close" id="yuk4">Cancel</a>
        <a href="/logout/" class="modal-close" id="yuk5">Good bye:(</a>
    </div>
  </div>

    {% else %}
    
    <div id="ajax">

    <div id="notvalid"></div>

    {% if messages %}
        <p class="messages">
            {% for message in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %} id="red">{{ message }}</p>
            {% endfor %}
        </p>
    {% endif %}
    
    <form method="POST" id="post-form">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" id="yuk1">login</button>
    </form>
    <br>

    <p>
    If you don't already have an account, <a href="/register" id="link"> click here! </a>
    </p>
    </div>

    </div>

    {% endif %}

    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <script src="{% static 'js/japa.js' %}"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    </body>
</html>

authentication/templates/register.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<title>Register</title>

		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type = "text/css" href="{% static 'css/styling.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">

	</head>

	<body>

    {% load crispy_forms_tags %}

    <div class = "container text-center mt-5 mb-5" id="contain_bg">

    {% if messages %}
        <p class="messages">
            {% for message in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %} id="red">{{ message }}</p>
            {% endfor %}
        </p>
    {% endif %}

        <form method="POST">
        {% csrf_token %}
        {{form|crispy}}

        <button type="submit" id="yuk2">register</button>
    </form>
    <br>

    <p>
    If you already have an account, <a href="/login" id="link"> click here! </a>
    </p>
    </div>

    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <script src="{% static 'js/japa.js' %}"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

	</body>
</html>