CurhatMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('thepost/', include('thepost.urls')),
    path('thereply/', include('thereply.urls')),
    path('testimoni/', include('testimoni.urls')),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.login_request, name='login'),
    path('api/', views.UserListView.as_view(), name=None),
    path('logout/', views.logout_request, name='logout'),
]

testimoni/urls.py
from django.urls import path
from . import views

app_name="testimoni"
urlpatterns = [
    path('isitesti/', views.testimoni, name='testimoni'),
    path('gettesti/', views.PostListView().as_view(), name='gettestimoni'),
    path('create/', views.PostCreateView.as_view(), name=None),
    path('<int:pk>/', views.PostDetailView.as_view(), name=None),
]

# PostListView.as_view()

thepost/urls.py
from django.urls import path
from .views import *

app_name = 'thepost'

urlpatterns = [
    path('', timeline, name='timeline'),
    path('search/', search, name='search'),
    path('api/', storyCurhatListView.as_view(), name=None)
]

thereply/urls.py
from django.urls import path
from . import views

app_name = 'thereply'

urlpatterns = [
    path('', views.reply, name='reply'),
    path('postreply/', views.ReplyListView.as_view(), name='postreply'),
    path('replies/', views.replies, name='replies'),
]

thepost/models.py
from django.db import models

class storyCurhat(models.Model):
    story = models.CharField(max_length=200, default='Curhat')
    tags = models.CharField(max_length=15, default='Tags')

    def __str__(self):
        return self.story

thereply/models.py
from django.db import models
from thepost.models import storyCurhat

class Reply(models.Model):
    reply = models.CharField(max_length=300)
    post = models.ForeignKey(storyCurhat, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.reply

    

thepost/forms.py
from django import forms
from .models import storyCurhat

class CurhatForm(forms.ModelForm):
    story = forms.CharField(max_length=200, label='Ada Cerita apa hari ini?', widget=forms.Textarea(attrs={'class':'form-control', 'required': True, }))
    tags = forms.CharField(max_length=15, label='Tags', widget=forms.TextInput(attrs={'class':'form-control', 'required': True, }))

    class Meta:
        model = storyCurhat
        fields = ['story', 'tags']

thepost/views.py
from .models import storyCurhat
from .forms import CurhatForm
from . import serializers
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.generics import ListAPIView
from django.shortcuts import render, redirect

class storyCurhatListView(generics.ListAPIView):
    queryset = storyCurhat.objects.all()
    serializer_class = serializers.storyCurhatSerializer

def timeline(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CurhatForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('thepost:timeline')
        
        else:
            timeline = {'formCurhat': CurhatForm(), 'listCurhat': storyCurhat.objects.all()}
        return render(request, 'timeline.html', timeline)
    else:
        return render(request, 'login.html')

def search(request):
    return render(request, 'search.html')

thepost/templates/navbar.html
{% load static %}
<nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-custom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'authentication:homepage' %}">
                <img src="{% static 'images/logo.png' %}" width="85" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav justify-content-center d-flex flex-fill">
                    <li class="nav-item active">
                        <a class="nav-link  navbar-center" href="{% url 'thepost:timeline' %}"><img src="{% static 'images/write.png' %}" width="50"></a>
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-center d-flex flex-fill">
                        <li class="nav-item active">
                            <a class="nav-link  navbar-center" href="{% url 'testimoni:testimoni' %}"><img src="{% static 'images/feedback.png' %}" width="50"></a>
                        </li>
                    </ul>
            </div>
        </div>
    </nav>

thepost/templates/search.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Search | CurhatMe</title>
</head>

<body>
    <div class="container text-center">
        <label id="labelreply" for="id_reply">Apa yang mau anda cari?</label>
            <!-- Search form -->
        <div class="md-form mt-0">
            <input class="form-control" type="text" placeholder="Search Tags" aria-label="Search" id="searchbox">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search">Search</button>
            <a href="{% url 'thepost:timeline' %}">
                    <button type="button" class="btn btn-outline-dark">Back</button>  
            </a>
        </div>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="thegridbottom">
                    <div class="card">

                    </div>
                </div>
            </div>
        </div>
    </div>      
    <script src="{% static 'js/script.js' %}"></script>
</body>

thepost/templates/timeline.html
{% load static %}

{% include "navbar.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/navstyle.css' %}"> 
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Timeline | CurhatMe</title>
</head>
<body>
    {% block content %}
    <div class="container text-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-sm-1"></div>
                <div class="form-group col-sm-10">
                    <label id="labelreply" for="id_reply">Ada cerita apa hari ini?</label>
                    {% for fields in formCurhat %}
                    <br>
                    {{ fields }}
                    {% endfor %}
                    <label id="labelreply" for="id_reply">Tags</label>
                    <input type="submit" class="btn btn-secondary btn-sm" value="Curhat" id="balas"></button>
                </div>
            </div>
        </form>
        <div id="flip">Timeline <br>
            <p style="font-size: xx-small;">(Click to Swipe Up and Down)</p>
        </div>
        <a href="{% url 'thepost:search' %}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search">Search Tags</button>
        </a>
        {% for i in listCurhat %}
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="thegridbottom">
                    <div class="card">  
                        <div class="card-header">
                            <p class="tags">#{{ i.tags }}</p>
                        </div>
                        <div class="card-body">
                            <p class="curhat">{{ i.story }}</p>
                            <a href="{% url 'thereply:reply' %}">
                                <img src="{% static 'images/reply.png' %}" width="35" alt="">
                                <p style="font-size: 1vw;">reply</p>
                            </a>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
        {% endfor %}
    </div>

    <script src="{% static 'js/script.js' %}"></script>
    {% endblock content %}
</body>
</html>