CurhatMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('thepost/', include('thepost.urls')),
    path('thereply/', include('thereply.urls')),
    path('testimoni/', include('testimoni.urls')),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.login_request, name='login'),
    path('api/', views.UserListView.as_view(), name=None),
    path('logout/', views.logout_request, name='logout'),
]

testimoni/urls.py
from django.urls import path
from . import views

app_name="testimoni"
urlpatterns = [
    path('isitesti/', views.testimoni, name='testimoni'),
    path('gettesti/', views.PostListView().as_view(), name='gettestimoni'),
    path('create/', views.PostCreateView.as_view(), name=None),
    path('<int:pk>/', views.PostDetailView.as_view(), name=None),
]

# PostListView.as_view()

thepost/urls.py
from django.urls import path
from .views import *

app_name = 'thepost'

urlpatterns = [
    path('', timeline, name='timeline'),
    path('search/', search, name='search'),
    path('api/', storyCurhatListView.as_view(), name=None)
]

thereply/urls.py
from django.urls import path
from . import views

app_name = 'thereply'

urlpatterns = [
    path('', views.reply, name='reply'),
    path('postreply/', views.ReplyListView.as_view(), name='postreply'),
    path('replies/', views.replies, name='replies'),
]

thereply/models.py
from django.db import models
from thepost.models import storyCurhat

class Reply(models.Model):
    reply = models.CharField(max_length=300)
    post = models.ForeignKey(storyCurhat, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.reply

    

thereply/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

thereply/views.py
from django.shortcuts import render, redirect
from .models import Reply
from .import forms
from .import serializers
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.generics import ListAPIView

def replies(request):
    return render(request, 'postreply.html')

def reply(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.ReplyForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('thereply:replies')

        else:
            form = forms.ReplyForm()
        return render(request, 'reply.html', {'form': form})

    else:
        return render(request, 'login.html')


class ReplyListView(generics.ListAPIView):
    queryset = Reply.objects.all()
    serializer_class = serializers.ReplySerializer

thereply/templates/postreply.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>CurhatMe</title>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/curhat.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-custom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'authentication:homepage' %}">
                <img src="{% static 'images/logo.png' %}" width="85" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav justify-content-center d-flex flex-fill">
                    <li class="nav-item active">
                        <a class="nav-link  navbar-center" href="{% url 'thepost:timeline' %}"><img src="{% static 'images/write.png' %}" width="50"></a>
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-center d-flex flex-fill">
                        <li class="nav-item active">
                            <a class="nav-link  navbar-center" href="{% url 'testimoni:testimoni' %}"><img src="{% static 'images/feedback.png' %}" width="50"></a>
                        </li>
                    </ul>
            </div>
        </div>
    </nav>

    <div class="button">
        <button class="search-btn" type="button" name="button" id="lihat">lihat reply</button>
    </div>

    <script type="text/javascript" src="{% static "js/reply.js" %}"></script>

</body>

thereply/templates/reply.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>CurhatMe</title>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/curhat.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-custom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'authentication:homepage' %}">
                <img src="{% static 'images/logo.png' %}" width="85" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav justify-content-center d-flex flex-fill">
                    <li class="nav-item active">
                        <a class="nav-link  navbar-center" href="{% url 'thepost:timeline' %}"><img src="{% static 'images/write.png' %}" width="50"></a>
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-center d-flex flex-fill">
                        <li class="nav-item active">
                            <a class="nav-link  navbar-center" href="{% url 'testimoni:testimoni' %}"><img src="{% static 'images/feedback.png' %}" width="50"></a>
                        </li>
                    </ul>
            </div>
        </div>
    </nav>

    <form action="{% url 'thereply:reply' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <a class="modal-trigger" id="labelreply" for="id_reply" href="#modal1">Mau balas apa?</a>
                    {% for fields in form %}
                    <br>
                    {{ fields }}
                    {% endfor %}
                <input type="submit" class="btn btn-secondary btn-sm" value="reply" id="balas"></button>
            </div>
        </div>
    </form>

    <!-- Modal Structure -->
    <div id="modal1" class="modal">
        <div class="modal-content">
            <p>tuliskan pendapatmu mengenai post tersebut!</p>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
        </div>
    </div>

    <script type="text/javascript" src="{% static "js/modal.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script
</body>